version: "3"
services:
  app:
    container_name: app
    restart: no
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
    environment:
      - MONGO_HOST=mongo
    volumes:
      - ./reports:/code/reports
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/
    ports:
      - "27017:27017"