version: "3"
services:
  app:
    container_name: app
    restart: always
    build: /Users/anemona/PycharmProjects/orders/
    ports:
      - "3000:3000"
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/
    ports:
      - "27017:27017"